@include('includes/session')
@include('includes/functions')
<html>
	@include('includes/layouts/head')
	<body>
		@include('includes/layouts/header')
		@yield('content')
		@include('includes/layouts/footer')
		@include('includes/analytics')
	</body>
</html>